// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_0rrK2Ag_rP0_eMT73R3DA0uv-7zyQew',
    appId: '1:752806802358:web:303d3198b1dd26dc648717',
    messagingSenderId: '752806802358',
    projectId: 'mfcfooddeliveryapp',
    authDomain: 'mfcfooddeliveryapp.firebaseapp.com',
    storageBucket: 'mfcfooddeliveryapp.firebasestorage.app',
    measurementId: 'G-WH616LQVRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHrvH5WCD9T1zohAHzLgNW3c_i5zJYekU',
    appId: '1:752806802358:android:1c406ab32f2e66de648717',
    messagingSenderId: '752806802358',
    projectId: 'mfcfooddeliveryapp',
    storageBucket: 'mfcfooddeliveryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeayGyy25v56hSGdsu0Zq64ETSEuaWAvY',
    appId: '1:752806802358:ios:c9704c7ce066ebc4648717',
    messagingSenderId: '752806802358',
    projectId: 'mfcfooddeliveryapp',
    storageBucket: 'mfcfooddeliveryapp.firebasestorage.app',
    iosClientId: '752806802358-4s46n8jrotgkuhahp9nhnhqboo18t7n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeayGyy25v56hSGdsu0Zq64ETSEuaWAvY',
    appId: '1:752806802358:ios:c9704c7ce066ebc4648717',
    messagingSenderId: '752806802358',
    projectId: 'mfcfooddeliveryapp',
    storageBucket: 'mfcfooddeliveryapp.firebasestorage.app',
    iosClientId: '752806802358-4s46n8jrotgkuhahp9nhnhqboo18t7n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mfc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_0rrK2Ag_rP0_eMT73R3DA0uv-7zyQew',
    appId: '1:752806802358:web:06e3c731ec05247b648717',
    messagingSenderId: '752806802358',
    projectId: 'mfcfooddeliveryapp',
    authDomain: 'mfcfooddeliveryapp.firebaseapp.com',
    storageBucket: 'mfcfooddeliveryapp.firebasestorage.app',
    measurementId: 'G-FRGE3016ST',
  );
}
